# Macro file for Gd Neutron Scintillator
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
/tracking/verbose 1
# 
# neutron 10 MeV to the direction (0.,0.,1.)
#
/gun/particle neutron
/gun/energy 10 MeV
#
/run/beamOn 5
